import {notFound} from "next/navigation";
import {ButtonLink} from "@/components/ui";
import {getCurrentUser} from "@/lib/auth/session";
import {competitionAcceptsEntries,competitionEntryCtaState,competitionIsPubliclyVisible} from "@/lib/competitions";
import {prisma} from "@/lib/prisma";

const money=(p:number)=>p===0?"FREE":new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(p/100);
const date=(d:Date)=>d.toLocaleString("en-GB",{day:"numeric",month:"short",year:"numeric",hour:"numeric",minute:"2-digit",hour12:true}).replace(" am","am").replace(" pm","pm").replace(","," ·");
const lines=(s:string|null)=>s?.split(/\r?\n/).map(x=>x.trim()).filter(Boolean)??[];
export default async function CompetitionPage({params}:{params:{slug:string}}){
 const user=await getCurrentUser();
 const competition=await prisma.competition.findUnique({where:{slug:params.slug},include:{prizes:{orderBy:{displayOrder:"asc"}},judges:{orderBy:{displayOrder:"asc"},select:{id:true,name:true,roleTitle:true,organisation:true,biography:true,judgingFocus:true,imageStorageKey:true,guestJudge:true}},results:{where:{publishedAt:{not:null}},take:6,orderBy:{placement:"asc"},include:{entry:{include:{dog:{select:{name:true,registryNumber:true}}}}}}}});
 if(!competition||competition.status === "CANCELLED"||(competition.status==="DRAFT"&&user?.role!=="ADMIN"))notFound();
 const accepting=competitionAcceptsEntries(competition.status,competition.opensAt,competition.closesAt)&&competition.entryFeePence===0;
 const galleryEnabled=competition.galleryVisible&&competitionIsPubliclyVisible(competition.status);
 const [gallery,count,ownedDogs,userEntries]=await Promise.all([
  prisma.competitionEntry.findMany({where:{competitionId:competition.id,status:{in:["SUBMITTED","FINALIST","WINNER"]}},select:{id:true,dog:{select:{name:true,registryNumber:true}}},orderBy:{submittedAt:"desc"},take:galleryEnabled?6:0}),
  prisma.competitionEntry.count({where:{competitionId:competition.id,status:{in:["SUBMITTED","FINALIST","WINNER"]}}}),
  user?prisma.dogIdentity.findMany({where:{ownerships:{some:{userId:user.id}}},select:{id:true}}):[],
  user?prisma.competitionEntry.findMany({where:{competitionId:competition.id,submittedById:user.id},select:{dogId:true,status:true}}):[]
 ]);
 const state=user?competitionEntryCtaState(ownedDogs.map(d=>d.id),userEntries,competition.maxEntriesPerDog):null;
 const cta=!accepting?null:!user?{href:"/signup",label:"Create account"}:state==="NO_DOG"?{href:"/register-dog",label:"Register dog"}:state==="EXHAUSTED"?{href:"#entries",label:"View your entries"}:{href:`/competitions/${competition.slug}/enter`,label:"Enter now"};
 const days=Math.max(0,Math.ceil((+competition.closesAt-Date.now())/86400000));
 const artwork=competition.heroImageType!=="PHOTOGRAPH";
 const proof=count?`${count} genuine ${count===1?"entry":"entries"}`:(competition.launchMessage||"Entries now open · be among the first");
 const facts=[[money(competition.entryFeePence)+" ENTRY",competition.entryFeePence?"Entry fee":"No payment"],[competition.eligibility==="UK_ONLY"?"UK ONLY":"INTERNATIONAL","Eligibility"],[days?`CLOSES IN ${days} ${days===1?"DAY":"DAYS"}`:"ENTRIES CLOSED",date(competition.closesAt)],[`${competition.maxEntriesPerDog} ENTRY${competition.maxEntriesPerDog===1?"":"IES"} PER DOG`,"Entry limit"],[competition.prizes.length?"STRUCTURED PRIZES":"PRIZE PACKAGE","Real prizes"]];
 return <main className={cta?"pb-24 md:pb-0":""}>
  <section className="mx-auto max-w-7xl px-4 py-5 sm:px-6 md:px-8"><div className={`overflow-hidden rounded-[2rem] bg-navy shadow-registry ${artwork?"grid lg:grid-cols-[minmax(0,1.35fr)_minmax(20rem,.65fr)]":"relative"}`}>
   <div className={`${artwork?"relative grid h-[240px] place-items-center overflow-hidden bg-navy sm:h-[360px] lg:h-[480px]":"absolute inset-0"}`}>{competition.heroStorageKey&&<><img aria-hidden="true" alt="" src={`/api/competition-hero/${competition.id}`} className={`absolute inset-0 h-full w-full ${artwork?"scale-110 object-cover opacity-20 blur-2xl":"object-cover opacity-70"}`} style={{objectPosition:competition.heroFocalPosition}}/><img src={`/api/competition-hero/${competition.id}`} alt={competition.heroAltText||`Promotional artwork for ${competition.title}`} className={`relative h-full w-full ${artwork?"object-contain p-3 sm:p-5":"object-cover"}`} style={{objectPosition:competition.heroFocalPosition}}/></>}</div>
   <div className={`${artwork?"p-5 text-white sm:p-8 lg:flex lg:flex-col lg:justify-center":"relative flex min-h-[420px] max-w-3xl flex-col justify-end bg-gradient-to-t from-navy via-navy/60 p-6 text-white sm:p-10"}`}><div className="flex flex-wrap gap-2"><span className="rounded-full bg-white px-3 py-1 text-xs font-extrabold text-navy">{money(competition.entryFeePence)}</span><span className="rounded-full bg-white/15 px-3 py-1 text-xs font-bold">{competition.eligibility==="UK_ONLY"?"UK only":"International"}</span></div><h1 className="mt-4 text-3xl font-extrabold leading-tight sm:text-5xl">{competition.title}</h1><p className="mt-3 text-base text-white/85 sm:text-lg">{competition.tagline||competition.theme}</p><p className="mt-4 font-bold">{days?`${days} days left · ${date(competition.closesAt)}`:"Entries closed"}</p><p className="mt-1 text-sm text-sky-100">{proof}</p>{cta&&<div className="mt-5"><ButtonLink href={cta.href}>{cta.label}</ButtonLink></div>}</div>
  </div></section>
  <section aria-label="Competition facts" className="mx-auto max-w-7xl px-4 sm:px-6 md:px-8"><dl className="grid grid-cols-2 gap-px overflow-hidden rounded-2xl border border-navy/10 bg-navy/10 md:grid-cols-5">{facts.map(([a,b])=><div key={a} className="bg-cream px-3 py-4"><dt className="text-xs font-extrabold text-navy">{a}</dt><dd className="mt-1 text-xs text-charcoal/65">{b}</dd></div>)}</dl></section>
  <section className="mx-auto grid max-w-7xl gap-6 px-4 py-8 sm:px-6 md:px-8 lg:grid-cols-[minmax(0,2fr)_minmax(18rem,1fr)]">
   <div className="min-w-0 space-y-7"><div><h2 className="text-2xl font-extrabold text-navy">Prizes & event</h2><details className="mt-3" open={competition.description.length<420}><summary className="cursor-pointer font-bold text-info">{competition.theme} · <span className="font-normal">Read event details</span></summary><p className="mt-3 max-w-3xl whitespace-pre-line leading-7 text-charcoal/80">{competition.description}</p></details></div>
   {competition.prizes.length?<div className="flex snap-x gap-3 overflow-x-auto pb-2">{competition.prizes.map((p,i)=><article key={p.id} className={`min-w-[15rem] flex-1 snap-start rounded-2xl border p-4 ${i===0?"border-info bg-skysoft/30":"border-navy/10"}`}><p className="registry-label">{p.placement}</p><h3 className="mt-1 text-lg font-extrabold text-navy">{p.title||"Prize"}</h3>{p.imageUrl&&<img src={p.imageUrl} alt={`${p.title||p.placement} prize`} className="mt-2 aspect-[4/3] w-full rounded-xl object-cover"/>}{p.valuePence!=null&&<p className="mt-1 font-bold text-info">Value {money(p.valuePence)}</p>}<p className="mt-2 line-clamp-3 text-sm">{p.description}</p>{p.sponsor&&<p className="mt-2 text-xs font-bold">By {p.sponsor}</p>}</article>)}</div>:<div className="rounded-2xl border-l-4 border-info bg-skysoft/30 p-5"><h3 className="font-extrabold text-navy">Prize package</h3><p className="mt-2 whitespace-pre-line leading-6">{competition.prizeSummary}</p></div>}
   {competition.judges.length>0&&<div><h2 className="text-xl font-extrabold text-navy">Judges</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{competition.judges.map(j=><details key={j.id} className="rounded-2xl border border-navy/10 p-4"><summary className="cursor-pointer font-bold text-navy">{j.name} <span className="font-normal text-charcoal/60">· {j.organisation||j.roleTitle||"Judge"}</span></summary>{j.judgingFocus&&<p className="mt-2 text-sm"><strong>Looking for:</strong> {j.judgingFocus}</p>}{j.biography&&<p className="mt-2 text-sm">{j.biography}</p>}</details>)}</div></div>}
   </div>
   <aside className="rounded-2xl bg-navy p-5 text-white"><h2 className="text-xl font-extrabold">How to enter</h2><ol className="mt-4 grid gap-3">{["Create account","Register dog","Upload photo","Submit entry"].map((x,i)=><li key={x} className="flex items-center gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-white font-bold text-navy">{i+1}</span><span className="font-bold">{x}</span></li>)}</ol>{cta&&<div className="mt-5"><ButtonLink href={cta.href}>{cta.label}</ButtonLink></div>}</aside>
  </section>
  <section id="entries" className="mx-auto max-w-7xl px-4 pb-8 sm:px-6 md:px-8">{gallery.length?<><h2 className="text-xl font-extrabold text-navy">Recent entries</h2><div className="mt-3 flex gap-3 overflow-x-auto">{gallery.map(e=><a key={e.id} href={`/dogs/${e.dog.registryNumber}`} className="min-w-[9rem]"><img src={`/api/competition-images/${e.id}`} alt={`${e.dog.name} competition entry`} className="aspect-square w-36 rounded-xl object-cover"/><span className="mt-1 block font-bold">{e.dog.name}</span></a>)}</div></>:<div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-skysoft/40 px-5 py-4"><p><strong>No public entries yet</strong> — yours could be one of the first.</p>{cta&&<ButtonLink href={cta.href}>Enter</ButtonLink>}</div>}</section>
  <section className="mx-auto max-w-7xl px-4 pb-10 sm:px-6 md:px-8"><div className="rounded-2xl border border-navy/10 p-5"><h2 className="text-xl font-extrabold text-navy">Rules, eligibility & important dates</h2><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-4"><div><dt className="font-bold">Opens</dt><dd>{date(competition.opensAt)}</dd></div><div><dt className="font-bold">Closes</dt><dd>{date(competition.closesAt)}</dd></div><div><dt className="font-bold">Eligibility</dt><dd>{competition.eligibility==="UK_ONLY"?"UK only":"International"}</dd></div><div><dt className="font-bold">Entries per dog</dt><dd>{competition.maxEntriesPerDog}</dd></div></dl><div className="mt-4 grid gap-2"><details><summary className="cursor-pointer font-bold text-info">Full competition rules</summary><p className="mt-2 whitespace-pre-line">{competition.rules}</p></details><details><summary className="cursor-pointer font-bold text-info">Photo guidelines</summary><p className="mt-2 whitespace-pre-line">{competition.imageGuidelines}</p></details>{competition.judgingCriteria&&<details><summary className="cursor-pointer font-bold text-info">Judging criteria</summary><ul className="mt-2 list-disc pl-5">{lines(competition.judgingCriteria).slice(0,5).map(x=><li key={x}>{x}</li>)}</ul></details>}</div>{cta&&<div className="mt-5"><ButtonLink href={cta.href}>{cta.label}</ButtonLink></div>}</div></section>
  {cta&&<div className="fixed inset-x-0 bottom-0 z-40 border-t border-navy/10 bg-cream/95 p-3 backdrop-blur md:hidden"><div className="mx-auto flex max-w-md items-center justify-between gap-3"><div><strong className="block text-navy">{money(competition.entryFeePence)}</strong><span className="text-xs">{days?`${days} days left`:"Closing soon"}</span></div><ButtonLink href={cta.href}>{cta.label}</ButtonLink></div></div>}
 </main>;
}
